name: Build with Org mode and deploy to Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tizero/alpine-emacs:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
        
    steps:
      - name: Checkout repo
        run: actions/checkout@v3
        
      - name: List files
        run: pwd && ls -al
        

