name: Build and publish with Org mode

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.1
      - name: Clone Doom to ~/.emacs.d
        run: git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
      - name: Get Doom's version
        id: doom-version
        run: |
          cd ~/.emacs.d
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Cache Doom's Install
        uses: actions/cache@v3
        with:
          path: ~/.emacs.d
          key: ${{ runner.os }}-doom-${{ steps.doom-version.outputs.hash }}
          
